project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Obesity Risk"
  author:
    - Akshay Venkatesan (av3157)
    - Shreya Kurdukar (sk5295)
  repo-url: https://github.com/av3157/ObesityRisk.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


