# Conclusion

After extensively exploring this health risk factors data set provided by the CDC, there are several noteworthy observations that we feel should be highlighted. 

1. The strata ("Race/Ethnicity", "Gender", and "Grade") have some correlation. That is, while exploring each of these strata, we ended up with the same conclusions pertaining to trends in the data. This is significant because all of the health risk factors described and plotted throughout this project affect the different strata in very similar ways. There are certainly differences between the sub-stratifications within these strata, but overall, the trends are comparable, suggesting that these health factors do not impact one strata more than another. 

2. One contradicting discovery was that despite an improvement in average health rates, the average obesity rates continued to worsen. Although this is a very concerning statistic, it provides us with very useful information: there may be a confounding variable contributing to the discrepancy or additional variables beyond the studied 4 health rates that are strongly linked with high obesity rates. Whichever of these may be causing the difference, more research must be done regardless. 

3. Over the course of two decades, we can see that obesity rates across all regions of the United States have increased steadily. However, the obesity rates of states in the Midwest and South are, on average, higher than any other region in the United States. Research has found that rural areas typically exhibit a more sedentary lifestyle and lower household income. Such factors may play a role in obesity onset, as inhabitants engage in less physical activity and may not have the financial means to support weight-loss endeavors. This opens another avenue for further investigation based on region alone. 
