# Data

## Technical Description

For this project, we will be using data from the CDC pertaining to youth health risk factors. The specific risk factors that we will be exploring are nutrition, physical activity, and obesity. The data is being collected by the Youth Risk Behavior Surveillance System, a set of surveys that tracks behaviors that can lead to poor health for students in high school (9th-12th grade). The data is owned by the Division of Nutrition, Physical Activity, and Obesity (DNPAO). Our data was created on July 22, 2016, last updated on January 29, 2021, and the meta-data was last updated on August 25, 2023. 

There are 31 columns and 40,100 rows in this data set as of the last update. The data contains a mix of strings and floats. Some of the columns that we plan to use in our analysis include "YearStart", "YearEnd", "LocationAbbr", "Topic", "Question", "Data_Value", "Sample_Size", "Total", "Gender", "Grade", and "Race/Ethnicity". In particular, the "LocationAbbr", Gender", "Grade", and "Race/Ethnicity" columns will inform us of specific demographics of each observation. We will use these to analyze how different demographics are impacted by the youth health risk factors.  

After taking a glance at the data, we immediately noticed that there are several "NA" values which will need to be dealt with before analyzing youth risks by the demographics listed above. There are also several columns that will not be needed for our analysis, so we will subset the data so that further data manipulation will be more efficient. We will save the data as a ".csv" file and then import the data using the "read_csv()" function in R.

Sources:

1. https://data.cdc.gov/Nutrition-Physical-Activity-and-Obesity/Nutrition-Physical-Activity-and-Obesity-Youth-Risk/vba9-s8jp 
2. https://www.cdc.gov/healthyyouth/data/yrbs/index.htm 

## Research Plan

Since we will be answering the four questions mentioned in the Introduction, we will break this section into four parts. Our data set contains several columns which will allow us to answer these questions. 

### Question 1: Race vs Obesity

In this section, we will tackle the question of whether certain races are more prone to obesity than others. We will use the "Class", "Data_Value", and "StratificationCategory1" columns for this analysis. The "Class" column informs us which health risk category the question pertains to; for this question, we will specifically filter for the "Obesity / Weight Status" class. The "Data_Value" column provides us information on the percentage of students that face the specified health risk. The "StratificationCategory1" column contains information on which demographic the data has been stratified on; for this question, we will group by "Race/Ethnicity" so that we can understand the obesity percentages by race. We will create a bar plot using the "ggplot2" library and plot the races on the x-axis and the obesity percentages on the y-axis. This will allow us to see which race(s) is the most prone to obesity. 

### Question 2: Lifestyle Choices vs Obesity 

In this section we will tackle the question of how lifestyle choices impact obesity rates. We will use the "Class", Data_Value", and "StratificationCategory1" columns for this analysis. The "Class" column informs us which health risk category the question pertains to; for this question, we will specifically filter out the "Obesity / Weight Status" class. In other words, we will keep all the rows containing the values "Physical Activity", "Sugar Drinks", Fruits and Vegetables", and "Television Viewing" since these are specific lifestyle choices. The "Data_Value" column provides us information on the percentage of students that face the specified health risk. The "StratificationCategory1" column contains information on which demographic the data has been stratified on; for this question, we will group by "Race/Ethnicity" so that we can understand the obesity rates by race. We will create a mosaic plot using the "ggplot2" library and plot the lifestyle choices and races on the horizontal-axis and the obesity percentages on the vertical-axis. This will allow us to see the impact of lifestyle choices by race on obesity rates. We will repeat this process for "Gender" and "Grade" stratifications and describe any differences in overall obesity rates.  

### Question 3: Location vs Obesity

In this question we will tackle the question of whether geographic locations of residence impact the onset of obesity. We will use the "Class", "Data_Value", and "LocationAbbr" columns for this analysis. The "Class" column informs us which health risk category the question pertains to; for this question, we will specifically filter for the "Obesity / Weight Status" class. The "Data_Value" column provides us information on the percentage of students that face the specified health risk. The "LocationAbbr" column contains state name abbreviations where the data samples were taken from; we will group by this column so that we can observe which states have the highest obesity percentages. We will create a bar plot using the "ggplot2" library and plot the state name abbreviations on the x-axis and the obesity percentages on the y-axis. This will allow us to see which state(s) has the highest obesity rate.  

### Question 4: Health Factors over Decade vs Obesity 

In this question we will tackle the question of how obesity rates change over a decade for all health factors. We will use the "YearEnd", Class", and "Data_Value" columns for this analysis. The "YearEnd" column tells us which year the data for a specific class, location, and stratification was last collected. Most of the data collection lasts one year for each observation but there are cases where the data collection lasts more than one year (i.e. "YearEnd" - "YearStart" > 0) and this is one potential issue we will have to deal with. The "Class" column informs us which health risk category the question pertains to; for this question, we will use all classes. The "Data_Value" column provides us information on the percentage of students that face the specified health risk.  We will create either an overlapping line graph or an overlapping ridge line plot using the "ggplot2" library and plot the years on the x-axis and the obesity rates on the y-axis. Each line graph/ridge line plot will be a different health factor. This will allow us to see which health factor(s) incurs the most change in obesity rates over time.


## Missing Value Analysis
